### ISSUE TITLE
Add a option to additional costs

### ISSUE THREAD

**Issue by iagosousadev** [lucasoares/tibia-calcs#24]
We usually have some kind of arrows or any other thing that doesn't have a cost and we don't have a way to add this to the whole party

so my suggestion is as follow: add a field "Additional Expenses" this will serve the whole party and it will just add this to the supply cost and divide among every party member

**Comment by lucasoares** [comment]
@luizcsm why not? Nice one to get back to this project haha

**Comment by iagosousadev** [comment]
@lucasoares o backend de vcs ta disponivel no git tbm? tentei usar o link que tem no repo aqui mas ele da inválido

**Comment by lucasoares** [comment]
> @lucasoares o backend de vcs ta disponivel no git tbm? tentei usar o link que tem no repo aqui mas ele da inválido

O website https://tibiacalcs.com/ não possui backend.

O que possui backend é um bot que temos no Discord que coleta informação de usuários para computar possíveis usuários "makers" (estilo TibiaRing).

E com isso a gente já tinha deixado a master preparada para receber (existe um Pull Request com o que foi feito).

Qual seu interesse nesse backend @iagosousadev ?

**Comment by iagosousadev** [comment]
@lucasoares entendi, achei que tivesse algum, não cheguei a olhar o código ainda por falta de tempo mas então creio que tudo deve ser feito no JS, até pensei em adicionar essa feature eu mesmo e mandar um pull request pra vcs porém ando muito sem tempo ultimamente :/ o pouquinho de tempo livre que to tendo eu vou jogar kkkkk mesmo assim obg pela informação. Boa noite :D

e força no projeto, ta bom demais.
